name: Terraform Pipeline

on:
  workflow_call:
    inputs:
      aws-role-arn:
        required: true
        type: string
      working-directory:
        required: false
        type: string
        default: '.'
      aws-region:
        required: false
        type: string
        default: ap-northeast-1
      environment-name:
        required: true
        type: string
      environment-url:
        required: false
        type: string
        default: ''
      terraform-version:
        required: false
        type: string
        default: '1.12.1'
  
permissions:
  id-token: write
  contents: read

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::211125421782:role/platform-github-actions-access
          aws-region: ap-northeast-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.terraform-version }}

      - name: Terraform Init
        working-directory: ${{ inputs.working-directory }}
        run: terraform init

      - name: Terraform Plan
        working-directory: ${{ inputs.working-directory }}
        run: terraform plan -out=tfplan

      - name: Save Plan as Text
        working-directory: ${{ inputs.working-directory }}
        run: terraform show -no-color tfplan > plan.txt

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ${{ inputs.working-directory }}/tfplan

  apply:
    name: Terraform Apply
    needs: plan
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment-name }}
      url: ${{ inputs.environment-url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::211125421782:role/platform-github-actions-access
          aws-region: ap-northeast-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.terraform-version }}

      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ${{ inputs.working-directory }}

      - name: Terraform Init
        working-directory: ${{ inputs.working-directory }}
        run: terraform init

      - name: Terraform Apply
        working-directory: ${{ inputs.working-directory }}
        run: terraform apply tfplan